from enum import Enum


class ObserverNotificationType(Enum):
    WATERING_PROGRAMS_DISABLED = "WATERING_PROGRAMS_DISABLED"
    NEXT_WATERING_TIME_CHANGED = "NEXT_WATERING_TIME_CHANGED"
    FIRESTORE_CLIENT_CHANGED = "FIRESTORE_CLIENT_CHANGED"
