from enum import Enum


class MessageType(Enum):
    ANY = "ANY"
    AUTO_WATERING_CYCLE = "AUTO_WATERING_CYCLE"
    MANUAL_WATERING_CYCLE = "MANUAL_WATERING_CYCLE"
    MOISTURE_LEVEL_MEASUREMENT = "MOISTURE_LEVEL_MEASUREMENT"
    LOW_WATER_LEVEL = "LOW_WATER_LEVEL"
    EMPTY_WATER_TANK = "EMPTY_WATER_TANK"
